# Generated by Django 4.2.4 on 2023-09-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
