# Generated by Django 4.2.4 on 2023-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0003_alter_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
