# Generated by Django 4.2.4 on 2023-09-12 10:51

from django.db import migrations, models
import django.utils.timezone
import person.models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_alter_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="active"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="uid",
            field=models.CharField(
                default=person.models.generate_id, editable=False, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.CharField(
                default=person.models.generate_id,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
